export const fileFieldsRegion = [
    'map',
    'monument',
    'playersDocuments',
    'loreBooks',
    'yardage',
    'bigYardage',
    'pit',
    'localRoads',
    'globalRoads',
    'warehouse',
    'barn',
    'seedbeds',
    'oneFloorHouse1',
    'oneFloorHouse2',
    'oneFloorHouse3',
    'oneFloorHouse4',
    'doubleFloorHouse1',
    'doubleFloorHouse2',
    'doubleFloorHouse3',
    'doubleFloorHouse4',
    'doubleFloorHouse5',
    'doubleFloorHouse6',
    'thirdFloorHouse1',
    'workshop1',
    'workshop2',
    'blacksmithShop',
    'religionOrCultureOrEconomicHouse1',
    'religionOrCultureOrEconomicHouse2',
    'marketPlace1',
    'marketPlace2',
    'marketPlace3',
    'marketPlace4',
    'marketPlace5',
    'stablesOrHarbor',
    'tavern',
    'importantBuilding',
    'greateBuilding',
    'steelBuilding',
    'preview',
] as const;

export type FileKeyRegion = (typeof fileFieldsRegion)[number];
