events{}
http {
  include /etc/nginx/mime.types;
  server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /discord/ {
      proxy_pass https://discord.com/api/;
      proxy_set_header Authorization "Bot $DISCORD_BOT_TOKEN";
      proxy_set_header Host discord.com;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_ssl_server_name on;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
