export const environment = {
    production: true,
    redirectUri: 'https://lasthearth.ru/home/',
    postLogoutRedirectUri: 'https://lasthearth.ru/home/',
    apiUrl: 'https://api.lasthearth.ru/v1',
    logtoEndpoint: 'https://logto.lasthearth.ru',
    discordScreenshotsChannelId: '1389973669576441897',
    discordGameChatChannelId: '1103295910617813033',
    discordDiplomacyChannelId: '1511350694916132925',
    eastSuzerain: '-',
    westSuzerain: '-',
    gameVersion: '1.22.2',
    siteVersion: '1.5.0',
    gameServerIp: 'play.lasthearth.ru',
    gameServerPassword: 'djA2n313IN728Olq99SlBr',
    teamPhotos: {
        Lisov: '/team/Lisov.webp',
        Yonhva: '/team/Yonhva.webp',
        ripls: '/team/Ripls.webp',
        Sunhell: '/team/Sunhell.webp',
        Hecker: '/team/Hecker.webp',
        'Mr.Suslik': '/team/Susl.webp',
        Myza: '/team/Myza.webp',
        Errora: '/team/Errora.webp',
        Anneta: '/team/Anneta.webp',
        _NickRim_: '/team/Nick.webp',
        Лягушка: '/team/Lagucha.webp',
        Glifider: '/team/Glif.webp',
        Minker: '/team/Minker.webp',
    } as Record<string, string>,
};
